# -*- coding: utf-8 -*-
"""内置符号库：写论文常用的数学符号全集，写作时直接查、复制 LaTeX。

- LaTeX 可直接粘贴进 Overleaf；
- Word 里用 MathType 的「Toggle TeX / 粘贴 TeX」同样识别；
- 论文里抽取的领域符号会与本表合并展示（见 symbols.library_symbols）。
每个条目：{"sym": 显示字符, "latex": 源码, "name": 中文名, "cat": 分类}
"""

SYMBOLS = [
    # ── 希腊字母（小写）──
    {"sym": "α", "latex": r"\alpha", "name": "alpha，常用于学习率/角度", "cat": "希腊字母"},
    {"sym": "β", "latex": r"\beta", "name": "beta，动量/系数", "cat": "希腊字母"},
    {"sym": "γ", "latex": r"\gamma", "name": "gamma，折扣因子/SNR", "cat": "希腊字母"},
    {"sym": "δ", "latex": r"\delta", "name": "delta，增量/扰动", "cat": "希腊字母"},
    {"sym": "ε", "latex": r"\varepsilon", "name": "epsilon，误差/探索率", "cat": "希腊字母"},
    {"sym": "θ", "latex": r"\theta", "name": "theta，参数/角度", "cat": "希腊字母"},
    {"sym": "λ", "latex": r"\lambda", "name": "lambda，正则化系数/波长", "cat": "希腊字母"},
    {"sym": "μ", "latex": r"\mu", "name": "mu，均值", "cat": "希腊字母"},
    {"sym": "ν", "latex": r"\nu", "name": "nu，频率/自由度", "cat": "希腊字母"},
    {"sym": "ξ", "latex": r"\xi", "name": "xi，随机扰动", "cat": "希腊字母"},
    {"sym": "ρ", "latex": r"\rho", "name": "rho，相关系数/密度", "cat": "希腊字母"},
    {"sym": "σ", "latex": r"\sigma", "name": "sigma，标准差", "cat": "希腊字母"},
    {"sym": "σ²", "latex": r"\sigma^2", "name": "方差", "cat": "希腊字母"},
    {"sym": "τ", "latex": r"\tau", "name": "tau，时间常数/温度", "cat": "希腊字母"},
    {"sym": "φ", "latex": r"\varphi", "name": "phi，相位/特征映射", "cat": "希腊字母"},
    {"sym": "χ", "latex": r"\chi", "name": "chi，卡方", "cat": "希腊字母"},
    {"sym": "ψ", "latex": r"\psi", "name": "psi，波函数/辅助函数", "cat": "希腊字母"},
    {"sym": "ω", "latex": r"\omega", "name": "omega，角频率/权重", "cat": "希腊字母"},
    # ── 希腊字母（大写常用）──
    {"sym": "Γ", "latex": r"\Gamma", "name": "Gamma 函数/伽马矩阵", "cat": "希腊字母"},
    {"sym": "Δ", "latex": r"\Delta", "name": "Delta，差分/变化量", "cat": "希腊字母"},
    {"sym": "Θ", "latex": r"\Theta", "name": "Theta，参数集合", "cat": "希腊字母"},
    {"sym": "Λ", "latex": r"\Lambda", "name": "Lambda，对角阵/正则阵", "cat": "希腊字母"},
    {"sym": "Π", "latex": r"\Pi", "name": "Pi，连乘", "cat": "希腊字母"},
    {"sym": "Σ", "latex": r"\Sigma", "name": "Sigma，求和/协方差阵", "cat": "希腊字母"},
    {"sym": "Φ", "latex": r"\Phi", "name": "Phi，特征矩阵/累积分布", "cat": "希腊字母"},
    {"sym": "Ω", "latex": r"\Omega", "name": "Omega，样本空间/频率矩阵", "cat": "希腊字母"},
    # ── 集合与数域 ──
    {"sym": "ℝ", "latex": r"\mathbb{R}", "name": "实数集", "cat": "集合与数域"},
    {"sym": "ℝⁿ", "latex": r"\mathbb{R}^n", "name": "n 维实向量空间", "cat": "集合与数域"},
    {"sym": "ℂ", "latex": r"\mathbb{C}", "name": "复数集", "cat": "集合与数域"},
    {"sym": "ℂ^(N×M)", "latex": r"\mathbb{C}^{N \times M}", "name": "N×M 复矩阵空间", "cat": "集合与数域"},
    {"sym": "ℤ", "latex": r"\mathbb{Z}", "name": "整数集", "cat": "集合与数域"},
    {"sym": "ℕ", "latex": r"\mathbb{N}", "name": "自然数集", "cat": "集合与数域"},
    {"sym": "∈", "latex": r"\in", "name": "属于", "cat": "集合与数域"},
    {"sym": "⊂", "latex": r"\subset", "name": "真子集", "cat": "集合与数域"},
    {"sym": "⊆", "latex": r"\subseteq", "name": "子集", "cat": "集合与数域"},
    {"sym": "∪", "latex": r"\cup", "name": "并集", "cat": "集合与数域"},
    {"sym": "∩", "latex": r"\cap", "name": "交集", "cat": "集合与数域"},
    {"sym": "∅", "latex": r"\emptyset", "name": "空集", "cat": "集合与数域"},
    {"sym": "|S|", "latex": r"\lvert S \rvert", "name": "集合基数/绝对值", "cat": "集合与数域"},
    # ── 范数与矩阵 ──
    {"sym": "‖x‖", "latex": r"\|\mathbf{x}\|", "name": "范数", "cat": "范数与矩阵"},
    {"sym": "‖x‖₂", "latex": r"\|\mathbf{x}\|_2", "name": "二范数（欧氏）", "cat": "范数与矩阵"},
    {"sym": "‖x‖∞", "latex": r"\|\mathbf{x}\|_\infty", "name": "无穷范数（最大元素）", "cat": "范数与矩阵"},
    {"sym": "‖X‖_F", "latex": r"\|\mathbf{X}\|_F", "name": "Frobenius 范数（矩阵）", "cat": "范数与矩阵"},
    {"sym": "xᵀ", "latex": r"\mathbf{x}^{\mathsf{T}}", "name": "转置", "cat": "范数与矩阵"},
    {"sym": "Xᴴ", "latex": r"\mathbf{X}^{H}", "name": "共轭转置（通信常用）", "cat": "范数与矩阵"},
    {"sym": "X⁻¹", "latex": r"\mathbf{X}^{-1}", "name": "逆矩阵", "cat": "范数与矩阵"},
    {"sym": "I_N", "latex": r"\mathbf{I}_N", "name": "N 阶单位阵", "cat": "范数与矩阵"},
    {"sym": "tr(X)", "latex": r"\operatorname{tr}(\mathbf{X})", "name": "矩阵的迹", "cat": "范数与矩阵"},
    {"sym": "det(X)", "latex": r"\det(\mathbf{X})", "name": "行列式", "cat": "范数与矩阵"},
    {"sym": "rank(A)", "latex": r"\operatorname{rank}(\mathbf{A})", "name": "矩阵秩", "cat": "范数与矩阵"},
    {"sym": "vec(X)", "latex": r"\operatorname{vec}(\mathbf{X})", "name": "矩阵向量化", "cat": "范数与矩阵"},
    {"sym": "⊗", "latex": r"\otimes", "name": "Kronecker 积", "cat": "范数与矩阵"},
    {"sym": "⊙", "latex": r"\odot", "name": "Hadamard 积（逐元素乘）", "cat": "范数与矩阵"},
    {"sym": "x̄", "latex": r"\bar{\mathbf{x}}", "name": "均值向量/共轭", "cat": "范数与矩阵"},
    {"sym": "x̂", "latex": r"\hat{\mathbf{x}}", "name": "估计值", "cat": "范数与矩阵"},
    # ── 微积分与优化 ──
    {"sym": "∇", "latex": r"\nabla", "name": "梯度/哈密顿算子", "cat": "微积分与优化"},
    {"sym": "∂", "latex": r"\partial", "name": "偏导数", "cat": "微积分与优化"},
    {"sym": "∑", "latex": r"\sum_{i=1}^{N}", "name": "求和（i 从 1 到 N）", "cat": "微积分与优化"},
    {"sym": "∏", "latex": r"\prod_{i=1}^{N}", "name": "连乘", "cat": "微积分与优化"},
    {"sym": "∫", "latex": r"\int", "name": "积分", "cat": "微积分与优化"},
    {"sym": "lim", "latex": r"\lim_{x \to \infty}", "name": "极限", "cat": "微积分与优化"},
    {"sym": "argmin", "latex": r"\operatorname*{argmin}_{x}", "name": "最小化自变量", "cat": "微积分与优化"},
    {"sym": "argmax", "latex": r"\operatorname*{argmax}_{x}", "name": "最大化自变量", "cat": "微积分与优化"},
    {"sym": "min", "latex": r"\min", "name": "最小值", "cat": "微积分与优化"},
    {"sym": "max", "latex": r"\max", "name": "最大值", "cat": "微积分与优化"},
    {"sym": "s.t.", "latex": r"\text{ s.t. }", "name": "受约束于", "cat": "微积分与优化"},
    {"sym": "ℒ", "latex": r"\mathcal{L}", "name": "损失函数/拉格朗日函数", "cat": "微积分与优化"},
    {"sym": "𝒪(·)", "latex": r"\mathcal{O}(\cdot)", "name": "计算复杂度上界", "cat": "微积分与优化"},
    {"sym": "𝒮", "latex": r"\mathcal{S}", "name": "集合/系统（花体）", "cat": "微积分与优化"},
    # ── 概率统计 ──
    {"sym": "𝒩(μ,σ²)", "latex": r"\mathcal{N}(\mu, \sigma^2)", "name": "高斯分布", "cat": "概率统计"},
    {"sym": "P(A)", "latex": r"P(A)", "name": "概率", "cat": "概率统计"},
    {"sym": "E[X]", "latex": r"\mathbb{E}[X]", "name": "期望", "cat": "概率统计"},
    {"sym": "Var(X)", "latex": r"\operatorname{Var}(X)", "name": "方差", "cat": "概率统计"},
    {"sym": "Cov(X,Y)", "latex": r"\operatorname{Cov}(X, Y)", "name": "协方差", "cat": "概率统计"},
    {"sym": "∼", "latex": r"\sim", "name": "服从分布/相似", "cat": "概率统计"},
    {"sym": "∝", "latex": r"\propto", "name": "成正比", "cat": "概率统计"},
    {"sym": "⟨x,y⟩", "latex": r"\langle \mathbf{x}, \mathbf{y} \rangle", "name": "内积", "cat": "概率统计"},
    # ── 逻辑与关系 ──
    {"sym": "→", "latex": r"\to", "name": "趋于/映射到", "cat": "逻辑与关系"},
    {"sym": "⇒", "latex": r"\Rightarrow", "name": "推出", "cat": "逻辑与关系"},
    {"sym": "⇔", "latex": r"\Leftrightarrow", "name": "等价", "cat": "逻辑与关系"},
    {"sym": "∀", "latex": r"\forall", "name": "任意", "cat": "逻辑与关系"},
    {"sym": "∃", "latex": r"\exists", "name": "存在", "cat": "逻辑与关系"},
    {"sym": "≈", "latex": r"\approx", "name": "近似等于", "cat": "逻辑与关系"},
    {"sym": "≠", "latex": r"\neq", "name": "不等于", "cat": "逻辑与关系"},
    {"sym": "≤", "latex": r"\leq", "name": "小于等于", "cat": "逻辑与关系"},
    {"sym": "≥", "latex": r"\geq", "name": "大于等于", "cat": "逻辑与关系"},
    {"sym": "±", "latex": r"\pm", "name": "正负号", "cat": "逻辑与关系"},
    {"sym": "×", "latex": r"\times", "name": "乘", "cat": "逻辑与关系"},
    {"sym": "·", "latex": r"\cdot", "name": "点乘", "cat": "逻辑与关系"},
    {"sym": "⊥", "latex": r"\perp", "name": "正交/统计独立", "cat": "逻辑与关系"},
    {"sym": "≜", "latex": r"\triangleq", "name": "定义为", "cat": "逻辑与关系"},
    {"sym": "∞", "latex": r"\infty", "name": "无穷大", "cat": "逻辑与关系"},
]
